version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    volumes:
      - ${PWD}/target/keycloak-account-v1-0.4-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-account-v1.jar
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8180:8180
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --http-port=8180